CREATE TABLE livro (
   id INT AUTO_INCREMENT PRIMARY KEY,
   titulo VARCHAR(255) NOT NULL,
   autor VARCHAR(255) NOT NULL,
   isbn VARCHAR(13) NOT NULL,
   editora VARCHAR(255) NOT NULL,
   ano INT NOT NULL
);
